######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 11 18:05:41 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h worker.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp worker.cpp
